/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MaximePages (https://sketchfab.com/pagesm)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/game-boy-color-277998bca398436faaece92470d93372
title: Game Boy Color
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Box001_default_0: THREE.Mesh
    Box001_default_0_1: THREE.Mesh
    ['Plane001_Material_#129_0']: THREE.Mesh
  }
  materials: {
    ['default']: THREE.MeshStandardMaterial
    default_0: THREE.MeshStandardMaterial
    Material_129: THREE.MeshPhysicalMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Box001_default_0.geometry} material={materials['default']} />
        <mesh geometry={nodes.Box001_default_0_1.geometry} material={materials.default_0} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Plane001_Material_#129_0'].geometry} material={materials.Material_129} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
